name: sidekick
description: Flutter Version Manager.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-alpha.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fvm:
    git:
      url: https://github.com/leoafarias/fvm.git
      ref: master
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  animations: ^2.0.0
  async: ^2.5.0
  date_time_format: ^2.0.1
  file_chooser: ^0.1.6
  filesize: ^1.0.4
  flutter_cache: ^0.1.0
  flutter_hooks: ^0.16.0
  flutter_spinkit: ^5.0.0
  github: ^7.0.4
  google_fonts: ^1.1.2
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  hooks_riverpod: ^0.12.4
  list_ext: ^1.0.2
  material_design_icons_flutter: ^4.0.5955
  material_floating_search_bar: ^0.3.3
  oktoast: ^3.0.0
  path_provider: ^2.0.1
  pub_api_client: ^1.0.9
  pubspec_yaml: ^2.0.1+1
  responsive_grid: ^2.0.0
  settings_ui: ^0.6.0
  truncate: ^3.0.1
  url_launcher: ^6.0.3
  watcher: ^1.0.0
  # flutter_luban: ^0.1.12
  flutter_luban:
    git:
      url: https://github.com/leoafarias/flutter_luban.git
      ref: master
  pool: ^1.5.0
  before_after: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  effective_dart: ^1.3.1
  hive_generator: ^1.0.0
  msix: ^0.1.19

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
